services:
  backend:
    image: samuelosondu001/video-call-backend:latest
    restart: unless-stopped
    networks:
      - swarm-global-network
    deploy:
      replicas: 1
    expose:
      - "3000"

  nginx:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/backapi.clearcomms.space:/etc/letsencrypt/live/backapi.clearcomms.space:ro
      - /etc/letsencrypt/archive/backapi.clearcomms.space:/etc/letsencrypt/archive/backapi.clearcomms.space:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
    depends_on:
      - backend
    networks:
      - swarm-global-network

networks:
  swarm-global-network:
    external: true
