name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (only for Docker context)
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: samuelosondu001/video-call-backend:latest
        env:
          DOCKER_BUILDKIT: 1

      - name: Set up SSH access to Droplet
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 52.27.98.238 >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Deploy on Droplet (auto-clone + deploy)
        run: |
          ssh -i ~/.ssh/id_ed25519 root@52.27.98.238 << 'EOF'
            set -e

            REPO_DIR="/root/call-feature"
            GIT_REPO="git@github.com:${{ github.repository }}.git"

            # Clone if not already cloned
            if [ ! -d "$REPO_DIR/.git" ]; then
              echo "Cloning repo for the first time..."
              git clone "$GIT_REPO" "$REPO_DIR"
            fi

            # Update repo and deploy
            cd "$REPO_DIR"
            git pull origin main

            docker pull samuelosondu001/video-call-backend:latest
            docker stack deploy --with-registry-auth -c docker-compose.yml call-feature
          EOF
